# Metadata
title: ReduxFlakes
author: Tiago Carmo
<<<<<<< HEAD
url: www.reduxflakes.ga
=======
url: https://www.reduxflakes.ga
>>>>>>> 751fdeb6c7a8803bda210b97c940d93937a82c4d
description: 🌼 • 15 | 📍 • Portugal | 💻 • Android app developer, Python | 
favicon: "./"

# Build Settings
remote_theme: abhinavs/moonwalk
markdown: kramdown

theme_config:
  appearance: "auto"
  back_home_text: "go back.."
  appearance_toggle: true
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true

  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_old_projects: true # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml

